--CRIA O BANCO DE DADOS
CREATE DATABASE INLOCK_GAMES_MANHA

--DEFINE O BANCO DE DADOS QUE SERÁ UTILIZADO
USE INLOCK_GAMES_MANHA

--CRIA A TABELA ESTUDIOS COM SUAS COLUNAS
CREATE TABLE ESTUDIOS(
	ESTUDIOID INT IDENTITY PRIMARY KEY
	,NOMEESTUDIO VARCHAR(250) UNIQUE NOT NULL
);

--CRIA A TABELA JOGOS COM SUAS COLUNAS
CREATE TABLE JOGOS(
	JOGOID INT IDENTITY PRIMARY KEY
	,NOMEJOGO VARCHAR(250) UNIQUE NOT NULL
	,DESCRICAO VARCHAR(250) UNIQUE NOT NULL
	,DATALANCAMENTO DATE NOT NULL
	,VALOR DECIMAL(10,2) NOT NULL
	,ESTUDIOID INT FOREIGN KEY REFERENCES ESTUDIOS(ESTUDIOID)
	--DEFINE O PAR DE ATRIBUTOS NOMEJOGO E DATALANCAMENTO COMO UM PAR ÚNICO
	,CONSTRAINT UC_JOGOS UNIQUE(NOMEJOGO,DATALANCAMENTO)
);

--CRIA A TABELA USUARIOS COM SUAS COLUNAS
CREATE TABLE USUARIOS(
	USUARIOID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(250) UNIQUE NOT NULL
	,SENHA VARCHAR(250) NOT NULL
	,TIPOUSUARIO VARCHAR(250) NOT NULL
);