--DEFINE O BANCO DE DADOS QUE SERÁ UTILIZADO
USE INLOCK_GAMES_MANHA;

--BUSCA TODOS OS USUÁRIOS
SELECT * FROM USUARIOS;

--BUSCA TODOS OS ESTÚDIOS
SELECT * FROM ESTUDIOS;

--BUSCA TODOS OS JOGOS
SELECT * FROM JOGOS;

--BUSCA TODOS OS JOGOS COM SEUS RESPECTIVOS ESTÚDIOS
SELECT
	J.NOMEJOGO, E.NOMEESTUDIO
FROM
	JOGOS J
INNER JOIN
	ESTUDIOS E
ON
	J.ESTUDIOID = E.ESTUDIOID;

--BUSCA TODOS OS ESTÚDIOS E SEUS JOGOS
--MESMO QUE UM ESTÚDIO NÃO TENHA UM JOGO REFERENCIADO
SELECT
	E.NOMEESTUDIO, J.NOMEJOGO
FROM
	ESTUDIOS E
LEFT JOIN
	JOGOS J
ON
	E.ESTUDIOID = J.ESTUDIOID;

--BUSCA UM USUÁRIO ATRAVÉS DO SEU EMAIL E SENHA
SELECT * FROM USUARIOS
WHERE EMAIL = 'admin@admin.com' AND SENHA = 'admin';

--BUSCA UM USUÁRIO ATRAVÉS DO SEU EMAIL E SENHA
SELECT * FROM USUARIOS
WHERE EMAIL = 'cliente@cliente.com' AND SENHA = 'cliente';

--BUSCA UM JOGO PELO SEU ID
SELECT * FROM JOGOS WHERE JOGOID = 1;
SELECT * FROM JOGOS WHERE JOGOID = 2;

--BUSCA UM ESTÚDIO PELO SEU ID
SELECT * FROM ESTUDIOS WHERE ESTUDIOID = 1;
SELECT * FROM ESTUDIOS WHERE ESTUDIOID = 2;
SELECT * FROM ESTUDIOS WHERE ESTUDIOID = 3;